<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="XE-INT-LAKSHYAG" name="test1" tests="2" failures="1" timestamp="27 May 2016 06:30:17 GMT" time="0.205" errors="0">
  <testcase name="testSomeMethod" time="0.066" classname="com.mycompany.pro.CalculatorTestNGTest"/>
  <testcase name="testSomeMethod2" time="0.002" classname="com.mycompany.pro.CalculatorTestNGTest">
    <failure type="java.lang.AssertionError" message="expected [20] but found [30]">
      <![CDATA[java.lang.AssertionError: expected [20] but found [30]
	at com.mycompany.pro.CalculatorTestNGTest.testSomeMethod2(CalculatorTestNGTest.java:29)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSomeMethod2 -->
</testsuite> <!-- test1 -->
